FROM picsellia/cuda:11.7.1-cudnn8-ubuntu20.04

COPY ./dataset/sanity_checks/requirements.txt .
ARG REBUILD_ALL
RUN pip3 install -r ./requirements.txt --no-cache-dir
ARG REBUILD_PICSELLIA

WORKDIR /experiment

COPY ./dataset/sanity_checks ./


ENTRYPOINT ["run", "main.py"]